# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
  path_filters:
    - "**/*"
